vich_uploader:
    db_driver: orm

    mappings:
       book_images:
           uri_prefix:          '%app.path.book_images%'
           upload_destination:  '%kernel.project_dir%/public%app.path.book_images%'
           namer:                Vich\UploaderBundle\Naming\UniqidNamer
